//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DtDc_Billing.Entity_FR
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminAccessPage
    {
        public int Id { get; set; }
        public string ModuleName { get; set; }
        public string Pfcode { get; set; }
        public string Accesspage { get; set; }
        public Nullable<System.DateTime> AcceessDate { get; set; }
    }
}
