//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DtDc_Billing.Entity_FR
{
    using System;
    using System.Collections.Generic;
    
    public partial class paymentLog
    {
        public long id { get; set; }
        public string Pfcode { get; set; }
        public string ownerName { get; set; }
        public Nullable<double> totalAmount { get; set; }
        public Nullable<long> registrationId { get; set; }
        public string paymentLogId { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> dateTime { get; set; }
        public string description { get; set; }
        public string paymentmethod { get; set; }
        public Nullable<System.DateTime> RenewalDate { get; set; }
        public string RenewalStatus { get; set; }
    }
}
