//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DtDc_Billing.Entity_FR
{
    using System;
    using System.Collections.Generic;
    
    public partial class registration
    {
        public long registrationId { get; set; }
        public string Pfcode { get; set; }
        public string franchiseName { get; set; }
        public string emailId { get; set; }
        public Nullable<System.DateTime> dateTime { get; set; }
        public string ownerName { get; set; }
        public string userName { get; set; }
        public string password { get; set; }
        public Nullable<bool> isPaid { get; set; }
        public string referralCode { get; set; }
        public string mobileNo { get; set; }
        public string address { get; set; }
        public string referralby { get; set; }
        public string GSTNo { get; set; }
        public string Pan_No { get; set; }
        public string AccountName { get; set; }
        public string BankName { get; set; }
        public string AccountNo { get; set; }
        public string IFSC_Code { get; set; }
        public string Branch { get; set; }
        public string AccountType { get; set; }
        public string InvoiceStart { get; set; }
        public string IsRenewal { get; set; }
        public string IsRenewalEmail { get; set; }
        public Nullable<System.DateTime> IsRenewalEmailDate { get; set; }
    }
}
